import { Toaster } from 'react-hot-toast';

import { Geist, Geist_Mono } from 'next/font/google';

import Provider from '@/src/app/providers/provider';

import type { Metadata } from 'next';

import './styles/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function App({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Provider>
                    <Toaster position="bottom-center" />
                    {children}
                </Provider>
            </body>
        </html>
    );
}
